[theme]
primaryColor = "#3B82F6"       # Electric Blue
backgroundColor = "#0B1220"    # Deep Navy
secondaryBackgroundColor = "#111827" # Steel
textColor = "#E5E7EB"          # Light Gray
font = "sans serif"
